### ISSUE TITLE
No contact names in group chats

### ISSUE THREAD

**Issue by timothymctim** [nanu-c/textsecure-qml#19]
### Description
In group chats, no information is displayed on who is sending which message. The only way to find out who sent the message, is by looking at the color of the message balloon.

### Steps to Reproduce

1. Create a group chat and invite some people.
2. Ask them to send a message.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always in group chats.

### Additional Information
In previous versions of this app, a block with the initials of the sender were shown. It would be great if this could be added back or if in some other way the name of the sender of a chat message could be displayed.

#### Versions
0.3.18 (at least)

#### Device
BQ Aquaris E4.5 Ubuntu Edition

**Comment by nanu-c** [comment]
This is solved in https://github.com/nanu-c/textsecure-qml/commit/0058269297d5c9f8d9f134a2f82eabd0870793bf and will be in the next release

**Comment by Flaburgan** [comment]
I still have this issue, I have a + instead of the name or avatar. 

Here is how it looks to me:

![screenshot20190727_223329608](https://user-images.githubusercontent.com/930064/61999363-8948c300-b0bf-11e9-884d-d5ecb320935c.png)

**Comment by nanu-c** [comment]
You have a + when the contact is not in your contact list. is that the case?

**Comment by Flaburgan** [comment]
It is indeed not in the app contact list, even if it is in the phone contact list. And importing contacts doesn't work.
