### ISSUE TITLE
App crashes upon entering the password

### ISSUE THREAD

**Issue by 1ploss** [nanu-c/textsecure-qml#28]
### Description

App crashes after entering the password.
It seems that my client tries to send unsent messages.
This happens even when the phone has no internet connection.

### Steps to Reproduce

1. Enable encrypted storage
1. Generate unsent messages
2. Update app to version 0.3.22
3. Restart app
4. Enter password

**Expected behavior:**
App runs

**Actual behavior:**
App crashes

**Reproduces how often:**
Issue is persistent on my phone. Restart does not help.
I don't have a second Ubuntu phone to test if I can reproduce it.

### Additional Information
Snippet from the logfile:
```
2018/04/18 18:02:37 .:0: Last frame took 43 ms to render.
INFO[0070] Connecting to encrypted data store           
2018/04/18 18:02:42 Loading Messages
INFO[0073] Db setup finished                            
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1d8d80]

goroutine 71 [running]:
panic(0x6a3278, 0x93c84038)
        /usr/local/go/src/runtime/panic.go:464 +0x330
github.com/aebruno/textsecure.(*store).sessionFilePath(0x0, 0x93dfb7d1, 0xc, 0x1, 0x0, 0x0)
        /gopath/src/github.com/aebruno/textsecure/store.go:376 +0x178
github.com/aebruno/textsecure.(*store).ContainsSession(0x0, 0x93dfb7d1, 0xc, 0x1, 0x94e7f4b8)
        /gopath/src/github.com/aebruno/textsecure/store.go:417 +0x38
github.com/aebruno/textsecure.buildMessage(0x93dfb7d0, 0xd, 0x93dff400, 0xa0, 0xa0, 0x94f6d6d0, 0x1, 0x1, 0x93c84500, 0x0, ...)
        /gopath/src/github.com/aebruno/textsecure/server.go:436 +0x138
github.com/aebruno/textsecure.buildAndSendMessage(0x93dfb7d0, 0xd, 0x93dff400, 0xa0, 0xa0, 0x93dff400, 0xa0, 0x0, 0x0)
        /gopath/src/github.com/aebruno/textsecure/server.go:497 +0xc4
github.com/aebruno/textsecure.sendMessage(0x94e5f540, 0x94e5f540, 0x1, 0x0, 0x0)
        /gopath/src/github.com/aebruno/textsecure/server.go:575 +0x334
github.com/aebruno/textsecure.SendMessage(0x93dfb7d0, 0xd, 0x93f45940, 0xb, 0x1, 0x93c9efc0, 0x0, 0x0)
        /gopath/src/github.com/aebruno/textsecure/textsecure.go:138 +0xa4
github.com/nanu-c/textsecure-qml/app/worker.SendMessageLoop(0x93dfb7d0, 0xd, 0x93f45940, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/nanu-c/textsecure-qml/app/worker/message.go:69 +0x32c
github.com/nanu-c/textsecure-qml/app/worker.SendMessage(0x93c95db0, 0x94f22a00)
        /gopath/src/github.com/nanu-c/textsecure-qml/app/worker/message.go:40 +0x15c
created by github.com/nanu-c/textsecure-qml/app/worker.SendUnsentMessages
        /gopath/src/github.com/nanu-c/textsecure-qml/app/worker/message.go:113 +0xf4
```
#### Versions
0.3.22

#### Device
MX4

#### Else
It seems that old unused messages are only send  on startup, if the device is connected to the internet.
Therefore the workaround for issue #24 may have caused a pile of unsent messages.

**Comment by nanu-c** [comment]
Found this, can I send you somehow the click for testing?

**Comment by 1ploss** [comment]
I have sent a email to your work mail address @nanu-c.
This way I don't have to make my address public. :)

**Comment by newsyy** [comment]
i have exactly the same issue, signal crashes every time just a moment after entering the password

**Comment by nanu-c** [comment]
@newsyy can you upload a log? Because the original failure is solved in the newest version in the open store.

**Comment by newsyy** [comment]
i got the latest update, restarted, but the issue persisted; i tried to figure out how to get get the logfile, but i'm not that tech savvy and so instead i exchanged my ubuntutouch for a lineage rom again, because signal is the main app i use on a phone. thanks tho!!!

**Comment by 1ploss** [comment]
This issue is fixed in 0.3.23.
Thank you very much. :)
